services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: # Docker volumes
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net

  kube_news:
    image: thiagopereira/kube-news:${KUBE_NEWS_TAG:-latest}
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      DB_DATABASE: ${POSTGRES_DB}
      DB_HOST: postgre # Nome do service do postgres


volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge