services:
  postgre:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pg#123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes: # Docker volumes
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net

  kube_news:
    image: thiagopereira/kube-news:latest
    build: 
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    environment:
      DB_PASSWORD: pg#123
      DB_USERNAME: kubenews
      DB_DATABASE: kubenews
      DB_HOST: postgre # Nome do service do postgres


volumes:
  postgre_docker_vol:

networks:
  kube_news_net:
    driver: bridge